name: $(Date:yyyyMMdd).$(Rev:r)

parameters:
- name: Sign
  displayName: "Signed"
  type: boolean
  default: false
- name: Publish
  displayName: "Publish"
  type: boolean
  default: false
- name: PreTest
  displayName: "Pre test"
  type: boolean
  default: true
- name: PostTest
  displayName: "Post test"
  type: boolean
  default: true
- name: TestSign
  displayName: "Test Signed"
  type: boolean
  default: false


variables:
  PIP_DISABLE_PIP_VERSION_CHECK: true
  PIP_NO_COLOR: true
  PIP_NO_INPUT: true
  PIP_PROGRESS_BAR: off
  PIP_REQUIRE_VIRTUALENV: false
  PIP_VERBOSE: true
  PYMSBUILD_VERBOSE: true
  PYMSBUILD_TEMP_DIR: $(Build.BinariesDirectory)
  DIST_DIR: $(Build.ArtifactStagingDirectory)
  LAYOUT_DIR: $(Build.BinariesDirectory)\layout
  PYMANAGER_PUBLISH_URL: https://example.com


jobs:
- job: Build

  pool:
    vmImage: 'windows-latest'

  variables:
  - ${{ if eq(parameters.Sign, 'true') }}:
    - group: CPythonSign
  - ${{ if eq(parameters.TestSign, 'true') }}:
    - group: CPythonTestSign
  - ${{ if eq(parameters.Publish, 'true') }}:
    - group: PythonOrgPublish


  steps:
  - checkout: self

  - task: NugetToolInstaller@0
    displayName: 'Install Nuget'

  - powershell: |
      nuget install -o host_python -x -noninteractive python
      Write-Host "##vso[task.prependpath]$(gi host_python\python\tools)"
    displayName: 'Install host Python'
    workingDirectory: $(Build.BinariesDirectory)

  - powershell: |
      python -m pip install pymsbuild
    displayName: 'Install build dependencies'

  - ${{ if eq(parameters.PreTest, 'true') }}:
    - powershell: |
        python -m pip install pytest
      displayName: 'Install test runner'

    - powershell: |
        python -m pymsbuild -c _msbuild_test.py
      displayName: 'Build test module'

    - powershell: |
        python -m pytest -vv
      displayName: 'Run pre-test'

  - ${{ if or(eq(parameters.Sign, 'true'), eq(parameters.TestSign, 'true')) }}:
    - powershell: |
        dotnet tool install sign --global
        cd (mkdir -Force signing)
        "*.exe", "*.pyd" | Out-File -Encoding UTF8 "signlist1.txt"
        Write-Host "##vso[task.setvariable variable=SIGNLIST1]$(gi signlist1.txt)"
        "*.msix" | Out-File -Encoding UTF8 "signlist2.txt"
        Write-Host "##vso[task.setvariable variable=SIGNLIST2]$(gi signlist2.txt)"
        "*.msi" | Out-File -Encoding UTF8 "signlist3.txt"
        Write-Host "##vso[task.setvariable variable=SIGNLIST3]$(gi signlist3.txt)"
      displayName: 'Install signing tool and generate files'
      workingDirectory: $(Build.BinariesDirectory)

  - powershell: |
      python make.py
    displayName: 'Build package'
    env:
      PYMSBUILD_LAYOUT_DIR: $(LAYOUT_DIR)
      PYMSBUILD_DIST_DIR: $(DIST_DIR)
      ${{ if or(eq(parameters.Sign, 'true'), eq(parameters.TestSign, 'true')) }}:
        PYMANAGER_APPX_PUBLISHER: $(TrustedSigningCertificateSubject)

  - ${{ if or(eq(parameters.Sign, 'true'), eq(parameters.TestSign, 'true')) }}:
    - powershell: >
        dir -r *.exe, *.pyd | %{
        sign code trusted-signing "$_"
        -fd sha256 -t http://timestamp.acs.microsoft.com -td sha256
        -tse "$(TrustedSigningUri)" -tsa "$(TrustedSigningAccount)" -tscp "$(TrustedSigningCertificateName)"
        -d "PyManager $(Build.BuildNumber)"
        -fl $env:SIGNLIST1
        }
      displayName: 'Sign binaries'
      workingDirectory: $(LAYOUT_DIR)

  - powershell: |
      python make-msix.py
    displayName: 'Build MSIX package'
    env:
      PYMSBUILD_LAYOUT_DIR: $(LAYOUT_DIR)
      PYMSBUILD_DIST_DIR: $(DIST_DIR)
      ${{ if or(eq(parameters.Sign, 'true'), eq(parameters.TestSign, 'true')) }}:
        PYMANAGER_APPX_PUBLISHER: $(TrustedSigningCertificateSubject)

  - powershell: |
      python make-msi.py
    displayName: 'Build MSI package'
    env:
      PYMSBUILD_LAYOUT_DIR: $(LAYOUT_DIR)
      PYMSBUILD_DIST_DIR: $(DIST_DIR)
      ${{ if or(eq(parameters.Sign, 'true'), eq(parameters.TestSign, 'true')) }}:
        PYMANAGER_APPX_PUBLISHER: $(TrustedSigningCertificateSubject)

  - ${{ if or(eq(parameters.Sign, 'true'), eq(parameters.TestSign, 'true')) }}:
    - powershell: >
        dir *.msix | %{
        sign code trusted-signing "$_"
        -fd sha256 -t http://timestamp.acs.microsoft.com -td sha256
        -tse "$(TrustedSigningUri)" -tsa "$(TrustedSigningAccount)" -tscp "$(TrustedSigningCertificateName)"
        -d "PyManager $(Build.BuildNumber)"
        -fl $env:SIGNLIST2
        }
      displayName: 'Sign MSIX package'
      workingDirectory: $(DIST_DIR)

    - powershell: >
        dir *.msi | %{
        sign code trusted-signing "$_"
        -fd sha256 -t http://timestamp.acs.microsoft.com -td sha256
        -tse "$(TrustedSigningUri)" -tsa "$(TrustedSigningAccount)" -tscp "$(TrustedSigningCertificateName)"
        -d "PyManager $(Build.BuildNumber)"
        -fl $env:SIGNLIST3
        }
      displayName: 'Sign MSI package'
      workingDirectory: $(DIST_DIR)

  - publish: $(DIST_DIR)
    artifact: dist
    displayName: Publish distribution artifacts

  - ${{ if eq(parameters.PostTest, 'true') }}:
    - powershell: |
        Write-Host "TODO: Post-build tests"
      displayName: 'TODO: Post-build tests'

  - ${{ if and(eq(parameters.Publish, 'true'), or(eq(parameters.Sign, 'true'), eq(parameters.TestSign, 'true'))) }}:
    - powershell: |
        Write-Host "TODO: Publish packages"
      displayName: 'TODO: Publish packages'
